version: '2'
services:
  collectd:
    build: collectd
    #pid: host
    #privileged: true
    volumes:
      - ./collectd-config/:/etc/collectd/collectd.conf.d/

  riemann:
    build: riemann
    hostname: riemann
    volumes:
      - ./riemann-config/riemann-collectd.config:/etc/riemann/riemann.config
